server.address=0.0.0.0
server.port=8080
spring.application.name=portfolio

# PostgreSQL Database Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/ReleasePortfolio
#spring.datasource.username=postgres
#spring.datasource.password=Sunxxl#567
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# h2 db setup
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#check

server.servlet.session.cookie.same-site=strict

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=0fa1154438351d
spring.mail.password=e7360854d2753a
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
