spring.application.name=portfolio

spring.datasource.url=jdbc:postgresql://localhost:5432/ReleasePortfolio
spring.datasource.username=postgres
spring.datasource.password=Sunxxl#567
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#spring.security.user.name=Suneel
#spring.security.user.password=1234
server.servlet.session.cookie.same-site=strict
